# Generated by Django 4.2 on 2026-03-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stream",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CA", "CA (Chartered Accountancy)"),
                    ("CLAT", "CLAT (Common Law Admission Test)"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
