# Generated by Django 4.2 on 2026-03-11 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_userprofile_email_userprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("study", "Study Session"),
                            ("case_note", "Case Note"),
                            ("revision", "Revision"),
                            ("mock_test", "Mock Test"),
                            ("research", "Research"),
                            ("other", "Other"),
                        ],
                        default="study",
                        max_length=20,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("is_pinned", models.BooleanField(default=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-date", "-created_at"],
            },
        ),
    ]
