# Generated by Django 4.2 on 2026-03-11 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_caseactivitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("question_solved", "Question Solved"),
                            ("study_session", "Study Session"),
                            ("note_created", "Note Created"),
                            ("quiz_taken", "Quiz Taken"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyActivitySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "date"], name="users_usera_user_id_889cc1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useractivity",
            unique_together={("user", "activity_type", "date")},
        ),
        migrations.AddIndex(
            model_name="dailyactivitysummary",
            index=models.Index(
                fields=["user", "date"], name="users_daily_user_id_0275d3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyactivitysummary",
            unique_together={("user", "date")},
        ),
    ]
