# Generated by Django 4.2 on 2026-04-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_useractivity_dailyactivitysummary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="audit_and_assurance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="audit_and_assurance_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="coporate_law",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="coporate_law_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Foundation", "Foundation"),
                    ("Intermediate", "Intermediate"),
                    ("Articleship", "Articleship"),
                ],
                default="Foundation",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="direct_taxation",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="direct_taxation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ethics_and_prof",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ethics_and_prof_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="financial_management",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="financial_management_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="financial_reporting",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="financial_reporting_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gst_and_indirect_tax",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gst_and_indirect_tax_count",
            field=models.IntegerField(default=0),
        ),
    ]
