# Generated by Django 4.2 on 2026-02-28 18:44

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notebooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=documents.models.user_file_path)),
                ("qdrant_collection", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notebooks.notebook",
                    ),
                ),
            ],
        ),
    ]
